# 1. Configuración de conexión
spring.datasource.url=jdbc:derby:derbydb;create=true
spring.datasource.username=app
spring.datasource.password=1234

# 2. Configuración JPA (Para crear tablas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.DerbyDialect

# 3. Configuración de inicialización de datos
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never