# 1. Configuración de conexión (Asegúrate de tener esto para que el esquema sea 'app' y no 'SA')
spring.datasource.url=jdbc:derby:derbydb;create=true
spring.datasource.username=app
spring.datasource.password=1234

# 2. Configuración JPA (Para crear tablas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.DerbyDialect

# 3. LA SOLUCIÓN MÁGICA (Añade esta línea al final)
spring.jpa.defer-datasource-initialization=true